/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HomeUI;

import ChildWelfareCentreUI.CWCentreHome;
import CommunityCareProviderUI.ComunityCareProvLogin;
import FosterCareUI.AdoptionFamilySignup;
import LegalUI.LoginPage;

/**
 *
 * @author nitan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnChildWelfareCentre = new javax.swing.JButton();
        btnChildProtectionService = new javax.swing.JButton();
        btnLawDepartment = new javax.swing.JButton();
        btnFosterCareCentre = new javax.swing.JButton();
        btnAdoption = new javax.swing.JButton();
        btnAdminLogin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHILD WELFARE SYSTEM");

        btnChildWelfareCentre.setBackground(new java.awt.Color(205, 195, 227));
        btnChildWelfareCentre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChildWelfareCentre.setText("CHILD WELFARE CENTRE");
        btnChildWelfareCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChildWelfareCentreActionPerformed(evt);
            }
        });

        btnChildProtectionService.setBackground(new java.awt.Color(205, 195, 227));
        btnChildProtectionService.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChildProtectionService.setText("CHILD PROTECTION SERVICE");
        btnChildProtectionService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChildProtectionServiceActionPerformed(evt);
            }
        });

        btnLawDepartment.setBackground(new java.awt.Color(205, 195, 227));
        btnLawDepartment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLawDepartment.setText("LAW DEPARTMENT");
        btnLawDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawDepartmentActionPerformed(evt);
            }
        });

        btnFosterCareCentre.setBackground(new java.awt.Color(205, 195, 227));
        btnFosterCareCentre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnFosterCareCentre.setText("FOSTER CARE CENTRE");
        btnFosterCareCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFosterCareCentreActionPerformed(evt);
            }
        });

        btnAdoption.setBackground(new java.awt.Color(205, 195, 227));
        btnAdoption.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdoption.setText("ADOPTION SIGNUP");
        btnAdoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptionActionPerformed(evt);
            }
        });

        btnAdminLogin1.setBackground(new java.awt.Color(205, 195, 227));
        btnAdminLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdminLogin1.setText("ADMIN LOGIN");
        btnAdminLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdminLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdoption, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFosterCareCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLawDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChildProtectionService)
                    .addComponent(btnChildWelfareCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(330, 330, 330))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChildWelfareCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnChildProtectionService, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnLawDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnFosterCareCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAdoption, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btnAdminLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChildProtectionServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChildProtectionServiceActionPerformed
        // TODO add your handling code here:
        ComunityCareProvLogin CCPV = new ComunityCareProvLogin();
            CCPV.show();
            dispose();
    }//GEN-LAST:event_btnChildProtectionServiceActionPerformed

    private void btnChildWelfareCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChildWelfareCentreActionPerformed
        // TODO add your handling code here:
        CWCentreHome CWCH = new CWCentreHome();
            CWCH.show();
            dispose();
    }//GEN-LAST:event_btnChildWelfareCentreActionPerformed

    private void btnLawDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawDepartmentActionPerformed
        // TODO add your handling code here:
        LegalUI.LoginPage LP = new LegalUI.LoginPage();
            LP.show();
            dispose();
    }//GEN-LAST:event_btnLawDepartmentActionPerformed

    private void btnAdoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptionActionPerformed
        // TODO add your handling code here:
        AdoptionFamilySignup LP = new AdoptionFamilySignup();
            LP.show();
            dispose();
    }//GEN-LAST:event_btnAdoptionActionPerformed

    private void btnFosterCareCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFosterCareCentreActionPerformed
        // TODO add your handling code here:
        FosterCareUI.LoginPage LP = new FosterCareUI.LoginPage();
            LP.show();
            dispose();
    }//GEN-LAST:event_btnFosterCareCentreActionPerformed

    private void btnAdminLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin1;
    private javax.swing.JButton btnAdoption;
    private javax.swing.JButton btnChildProtectionService;
    private javax.swing.JButton btnChildWelfareCentre;
    private javax.swing.JButton btnFosterCareCentre;
    private javax.swing.JButton btnLawDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
